import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import InvoiceFromSection from '../components/InvoiceFromSection'
import styles from '../styles/Home.module.css'


import React, { useState, useRef, forwardRef, useEffect } from 'react';
import { PDFExport } from '@progress/kendo-react-pdf';
import ImageUploading, { ImageListType } from 'react-images-uploading';
import SignaturePad from 'react-signature-canvas'
import DatePicker, { DateObject, getAllDatesInRange } from "react-multi-date-picker"
import DatePanel from "react-multi-date-picker/plugins/date_panel"
import { format } from 'date-fns'

const Home: NextPage = () => {

  /*  */

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin='crossorigin' />
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet"></link>
        <link href='' />


      </Head>

      {/* <body> */}

      

      
      <InvoiceFromSection />



      {/* </body> */}
    </div>
  )
}

export default Home


